version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Application.Dockerfile
    container_name: poke_app
    depends_on:
      - database
    restart: always
    ports:
      - 8080:8080
    networks:
      - poke_network

  database:
    build:
      context: .
      dockerfile: Database.Dockerfile
    container_name: poke_database
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: MyPass-1
      MYSQL_DATABASE: pkmn
      MYSQL_USER: root
      MYSQL_PASSWORD: MyPass-1
    restart: always
    ports:
      - 3306:3306
    networks:
      - poke_network

networks:
  poke_network:
    name: poke_network
    driver: bridge
